name: "CI"

on:
  pull_request:
  push:
    branches:
      - "v[0-9]+"

jobs:

  # Make sure build/ci work properly.
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
      - run: "npm install"
      - run: "npm run all"
      - uses: "codecov/codecov-action@v1"

  # Make sure the action works on a clean machine without building.
  test:
    name: "Test"
    runs-on: "${{ matrix.operating-system }}"
    continue-on-error: "${{ matrix.continue-on-error }}"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        dependency-versions:
          - "lowest"
          - "highest"
          - "locked"
        composer-options:
          - "--ignore-platform-reqs"
          - ""
        working-directory:
          - "subdirectory"
          - ""
        continue-on-error: [false]
        include:
          - continue-on-error: true
            operating-system: "ubuntu-latest"
            dependency-versions: "locked"
            composer-options: "--unknown-option"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
      - uses: ./
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
          composer-options: "${{ matrix.composer-options }}"
          working-directory: "${{ matrix.working-directory }}"
